# Generated by Django 4.1.4 on 2023-02-03 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MyEmpoyee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("second_name", models.CharField(max_length=20)),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Employee Email"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Patient Name")),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=30, verbose_name="Phone Number")),
                (
                    "email_address",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Patient Email"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, verbose_name="Event Name")),
                ("description", models.TextField(blank=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("employees", models.ManyToManyField(blank=True, to="base.myempoyee")),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="base.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduling",
                "verbose_name_plural": "Scheduling",
            },
        ),
    ]
