# Generated by Django 4.1.4 on 2023-02-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_events_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.patient",
            ),
        ),
    ]
